conditioning:
  method: mcg
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: gamma_blur
    gamma: 4.0
    gain: 0.5

  noise: 
    name: gaussian
    sigma: 0.05
